export const dados = [
  {
    id: 1,
    autor: "Miguel de Cervantes",
    titulo: "Dom Quixote",
    tipo: "Aventura e Romance",
    lancamento: "1605",
    img: "../../src/assets/dom_quixote_hq_9788525433633_hd.png",
  },
  {
    id: 2,
    autor: "Gege Akutami",
    titulo: "Jujutsu Kaisen Vol.23",
    tipo: "Romance",
    lancamento: "1881",
    img: "../../src/assets/Yuki.webp",
  },
  {
    id: 3,
    autor: "Machado de Asis",
    titulo: "Helena",
    tipo: "Romance",
    lancamento: "1876",
    img: "../../src/assets/Helena.jpg",
  },
  {
    id: 4,
    autor: "Clarice Linspector",
    titulo: "Hora da Estrela",
    tipo: "Romance",
    lancamento: "1977",
    img: "../../src/assets/capa-livro-hora-da-estrela.webp",
  },
  {
    id: 5,
    autor: "J.K. Rowling",
    titulo: "Harry Potter e a Pedra Filosofal",
    tipo: "Fantasia e Aventura",
    lancamento: "1997",
    img: "../../src/assets/Harry_Potter.jpg",
  },
  {
    id: 6,
    autor: "Dante Alighieri",
    titulo: "A Divina Comédia",
    tipo: "Poesia",
    lancamento: "1321",
    img: "../../src/assets/divina_comedia.jpg",
  },
  {
    id: 7,
    autor: "Osamu Tezuka",
    titulo: "Astroboy",
    tipo: "Mangá",
    lancamento: "1952",
    img: "../../src/assets/astroboy.png",
  },
  {
    id: 8,
    autor: "Tomoyo Shiino",
    titulo: "My Broken Mariko",
    tipo: "Mangá",
    lancamento: "2020",
    img: "../../src/assets/Mariko.jpg",
  },
  {
    id: 9,
    autor: "Gege Akutami",
    titulo: "Jujutsu Kaisen Vol.11",
    tipo: "Poesia",
    lancamento: "2020",
    img: "../../src/assets/JJK11.webp",
  },
  {
    id: 9,
    autor: "Kotteri",
    titulo: "Veil",
    tipo: "Mangá",
    lancamento: "2024",
    img: "../../src/assets/Veil.jpg",
  },
]